---
title: "Data_Sorting"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Before we start building the dashboard, we need to do some preparation:

```{r, attr.source='.numberLines'}
library(plyr) #For function revalue()
```

We first extract the wanted columns from the dataset we obtain from previous task:
```{r}
all_data = read.csv("All_location_data.csv")
# Read the csv file we obtain from task C

all_data = as.data.frame(cbind(all_data$BusinessName,
                               all_data$BusinessType,
                               all_data$RatingValue,
                               all_data$Geocode.Longitude,
                               all_data$Geocode.Latitude,
                               all_data$LocalAuthorityName))
# We trim down the dataset, only having the Business name, Business Type, Ratings,
# Longitude, Latitude and the corresponding area.

colnames(all_data) = c("BusinessName","BusinessType","Rating","Longitude","Latitude","Area")
# Rename the columns with names for easier understanding

all_data$Rating = revalue(all_data$Rating, c("AwaitingInspection" = "Awaiting Inspection", "AwaitingPublication" = "Awaiting Publication"))
# Change levels to a unified level where they have the same meaning 

write.csv(all_data,"All_location_data_cut.csv")
# write the csv
```

```{r, message=FALSE, echo=FALSE}
All_non_Scotland_Area = list("Adur" = "Adur",
                             "Allerdale" = "Allerdale",
                             "Amber Valley" = "Amber Valley",
                             "Anglesey" = "Anglesey",
                             "Antrim and Newtownabbey" = "Antrim and Newtownabbey",
                             "Ards and North Down" = "Ards and North Down",
                             "Armagh City, Banbridge and Craigavon" = "Armagh City, Banbridge and Craigavon",
                             "Arun" = "Arun",
                             "Ashfield" = "Ashfield",
                             "Ashford" = "Ashford",
                             "Babergh" = "Babergh",
                             "Barking and Dagenham" = "Barking and Dagenham",
                             "Barnet" = "Barnet",
                             "Barnsley" = "Barnsley",
                             "Barrow-in-Furness" = "Barrow-in-Furness",
                             "Basildon" = "Basildon",
                             "Basingstoke and Deane" = "Basingstoke and Deane",
                             "Bassetlaw" = "Bassetlaw",
                             "Bath and North East Somerset" = "Bath and North East Somerset",
                             "Bedford" = "Bedford",
                             "Belfast City" = "Belfast City",
                             "Bexley" = "Bexley",
                             "Birmingham" = "Birmingham",
                             "Blaby" = "Blaby",
                             "Blackburn" = "Blackburn",
                             "Blackpool" = "Blackpool",
                             "Blaenau Gwent" = "Blaenau Gwent",
                             "Bolsover" = "Bolsover",
                             "Bolton" = "Bolton",
                             "Boston" = "Boston",
                             "Bournemouth, Christchurch and Poole" = "Bournemouth, Christchurch and Poole",
                             "Bracknell Forest" = "Bracknell Forest",
                             "Bradford" = "Bradford",
                             "Braintree" = "Braintree",
                             "Breckland" = "Breckland",
                             "Brent" = "Brent",
                             "Brentwood" = "Brentwood",
                             "Bridgend" = "Bridgend",
                             "Brighton and Hove" = "Brighton and Hove",
                             "Bristol" = "Bristol",
                             "Broadland" = "Broadland",
                             "Bromley" = "Bromley",
                             "Bromsgrove" = "Bromsgrove",
                             "Broxbourne" = "Broxbourne",
                             "Broxtowe" = "Broxtowe",
                             "Buckinghamshire" = "Buckinghamshire",
                             "Burnley" = "Burnley",
                             "Bury" = "Bury",
                             "Caerphilly" = "Caerphilly",
                             "Calderdale" = "Calderdale",
                             "Cambridge City" = "Cambridge City",
                             "Camden" = "Camden",
                             "Cannock Chase" = "Cannock Chase",
                             "Canterbury City" = "Canterbury City",
                             "Cardiff" = "Cardiff",
                             "Carlisle City" = "Carlisle City",
                             "Carmarthenshire" = "Carmarthenshire",
                             "Castle Point" = "Castle Point",
                             "Causeway Coast and Glens" = "Causeway Coast and Glens",
                             "Central Bedfordshire" = "Central Bedfordshire",
                             "Ceredigion" = "Ceredigion",
                             "Charnwood" = "Charnwood",
                             "Chelmsford" = "Chelmsford",
                             "Cheltenham" = "Cheltenham",
                             "Cherwell" = "Cherwell",
                             "Cheshire East" = "Cheshire East",
                             "Cheshire West and Chester" = "Cheshire West and Chester",
                             "Chesterfield" = "Chesterfield",
                             "Chichester" = "Chichester",
                             "Chorley" = "Chorley",
                             "City of London Corporation" = "City of London Corporation",
                             "Colchester" = "Colchester",
                             "Conwy" = "Conwy",
                             "Copeland" = "Copeland",
                             "Corby" = "Corby",
                             "Cornwall" = "Cornwall",
                             "Cotswold" = "Cotswold",
                             "Coventry" = "Coventry",
                             "Craven" = "Craven",
                             "Crawley" = "Crawley",
                             "Croydon" = "Croydon",
                             "Dacorum" = "Dacorum",
                             "Darlington" = "Darlington",
                             "Dartford" = "Dartford",
                             "Daventry" = "Daventry",
                             "Denbighshire" = "Denbighshire",
                             "Derby City" = "Derby City",
                             "Derbyshire Dales" = "Derbyshire Dales",
                             "Derry City and Strabane" = "Derry City and Strabane",
                             "Doncaster" = "Doncaster",
                             "Dorset" = "Dorset",
                             "Dover" = "Dover",
                             "Dudley" = "Dudley",
                             "Durham" = "Durham",
                             "Ealing" = "Ealing",
                             "East Cambridgeshire" = "East Cambridgeshire",
                             "East Devon" = "East Devon",
                             "East Hampshire" = "East Hampshire",
                             "East Hertfordshire" = "East Hertfordshire",
                             "East Lindsey" = "East Lindsey",
                             "East Northamptonshire" = "East Northamptonshire",
                             "East Riding of Yorkshire" = "East Riding of Yorkshire",
                             "East Staffordshire" = "East Staffordshire",
                             "East Suffolk" = "East Suffolk",
                             "Eastbourne" = "Eastbourne",
                             "Eastleigh" = "Eastleigh",
                             "Eden" = "Eden",
                             "Elmbridge" = "Elmbridge",
                             "Enfield" = "Enfield",
                             "Epping Forest" = "Epping Forest",
                             "Epsom and Ewell" = "Epsom and Ewell",
                             "Erewash" = "Erewash",
                             "Exeter City" = "Exeter City",
                             "Fareham" = "Fareham",
                             "Fenland" = "Fenland",
                             "Fermanagh and Omagh" = "Fermanagh and Omagh",
                             "Flintshire" = "Flintshire",
                             "Folkestone and Hythe" = "Folkestone and Hythe",
                             "Forest of Dean" = "Forest of Dean",
                             "Fylde" = "Fylde",
                             "Gateshead" = "Gateshead",
                             "Gedling" = "Gedling",
                             "Gloucester City" = "Gloucester City",
                             "Gosport" = "Gosport",
                             "Gravesham" = "Gravesham",
                             "Great Yarmouth" = "Great Yarmouth",
                             "Greenwich" = "Greenwich",
                             "Guildford" = "Guildford",
                             "Gwynedd" = "Gwynedd",
                             "Hackney" = "Hackney",
                             "Halton" = "Halton",
                             "Hambleton" = "Hambleton",
                             "Hammersmith and Fulham" = "Hammersmith and Fulham",
                             "Harborough" = "Harborough",
                             "Haringey" = "Haringey",
                             "Harlow" = "Harlow",
                             "Harrogate" = "Harrogate",
                             "Harrow" = "Harrow",
                             "Hart" = "Hart",
                             "Hartlepool" = "Hartlepool",
                             "Hastings" = "Hastings",
                             "Havant" = "Havant",
                             "Havering" = "Havering",
                             "Herefordshire" = "Herefordshire",
                             "Hertsmere" = "Hertsmere",
                             "High Peak" = "High Peak",
                             "Hillingdon" = "Hillingdon",
                             "Hinckley and Bosworth" = "Hinckley and Bosworth",
                             "Horsham" = "Horsham",
                             "Hounslow" = "Hounslow",
                             "Hull and Goole Port" = "Hull and Goole Port",
                             "Hull City" = "Hull City",
                             "Huntingdonshire" = "Huntingdonshire",
                             "Hyndburn" = "Hyndburn",
                             "Ipswich" = "Ipswich",
                             "Isle of Wight" = "Isle of Wight",
                             "Isles of Scilly" = "Isles of Scilly",
                             "Islington" = "Islington",
                             "Kensington and Chelsea" = "Kensington and Chelsea",
                             "Kettering" = "Kettering",
                             "King's Lynn and West Norfolk" = "King's Lynn and West Norfolk",
                             "Kingston-Upon-Thames" = "Kingston-Upon-Thames",
                             "Kirklees" = "Kirklees",
                             "Knowsley" = "Knowsley",
                             "Lambeth" = "Lambeth",
                             "Lancaster City" = "Lancaster City",
                             "Leeds" = "Leeds",
                             "Leicester City" = "Leicester City",
                             "Lewes" = "Lewes",
                             "Lewisham" = "Lewisham",
                             "Lichfield" = "Lichfield",
                             "Lincoln City" = "Lincoln City",
                             "Lisburn and Castlereagh City" = "Lisburn and Castlereagh City",
                             "Liverpool" = "Liverpool",
                             "Luton" = "Luton",
                             "Maidstone" = "Maidstone",
                             "Maldon" = "Maldon",
                             "Malvern Hills" = "Malvern Hills",
                             "Manchester" = "Manchester",
                             "Mansfield" = "Mansfield",
                             "Medway" = "Medway",
                             "Melton" = "Melton",
                             "Mendip" = "Mendip",
                             "Merthyr Tydfil" = "Merthyr Tydfil",
                             "Merton" = "Merton",
                             "Mid and East Antrim" = "Mid and East Antrim",
                             "Mid Devon" = "Mid Devon",
                             "Mid Suffolk" = "Mid Suffolk",
                             "Mid Sussex" = "Mid Sussex",
                             "Mid Ulster" = "Mid Ulster",
                             "Middlesbrough" = "Middlesbrough",
                             "Milton Keynes" = "Milton Keynes",
                             "Mole Valley" = "Mole Valley",
                             "Monmouthshire" = "Monmouthshire",
                             "Neath Port Talbot" = "Neath Port Talbot",
                             "New Forest" = "New Forest",
                             "Newark and Sherwood" = "Newark and Sherwood",
                             "Newcastle-Under-Lyme" = "Newcastle-Under-Lyme",
                             "Newcastle Upon Tyne" = "Newcastle Upon Tyne",
                             "Newham" = "Newham",
                             "Newport" = "Newport",
                             "Newry, Mourne and Down" = "Newry, Mourne and Down",
                             "North Devon" = "North Devon",
                             "North East Derbyshire" = "North East Derbyshire",
                             "North East Lincolnshire" = "North East Lincolnshire",
                             "North Hertfordshire" = "North Hertfordshire",
                             "North Kesteven" = "North Kesteven",
                             "North Lincolnshire" = "North Lincolnshire",
                             "North Norfolk" = "North Norfolk",
                             "North Somerset" = "North Somerset",
                             "North Tyneside" = "North Tyneside",
                             "North Warwickshire" = "North Warwickshire",
                             "North West Leicestershire" = "North West Leicestershire",
                             "Northampton" = "Northampton",
                             "Northumberland" = "Northumberland",
                             "Norwich City" = "Norwich City",
                             "Nottingham City" = "Nottingham City",
                             "Nuneaton and Bedworth" = "Nuneaton and Bedworth",
                             "Oadby and Wigston" = "Oadby and Wigston",
                             "Oldham" = "Oldham",
                             "Oxford City" = "Oxford City",
                             "Pembrokeshire" = "Pembrokeshire",
                             "Pendle" = "Pendle",
                             "Peterborough City" = "Peterborough City",
                             "Plymouth City" = "Plymouth City",
                             "Portsmouth" = "Portsmouth",
                             "Powys" = "Powys",
                             "Preston" = "Preston",
                             "Reading" = "Reading",
                             "Redbridge" = "Redbridge",
                             "Redcar and Cleveland" = "Redcar and Cleveland",
                             "Redditch" = "Redditch",
                             "Reigate and Banstead" = "Reigate and Banstead",
                             "Rhondda Cynon Taf" = "Rhondda Cynon Taf",
                             "Ribble Valley" = "Ribble Valley",
                             "Richmond-Upon-Thames" = "Richmond-Upon-Thames",
                             "Richmondshire" = "Richmondshire",
                             "River Tees" = "River Tees",
                             "Rochdale" = "Rochdale",
                             "Rochford" = "Rochford",
                             "Rossendale" = "Rossendale",
                             "Rother" = "Rother",
                             "Rotherham" = "Rotherham",
                             "Rugby" = "Rugby",
                             "Runnymede" = "Runnymede",
                             "Rushcliffe" = "Rushcliffe",
                             "Rushmoor" = "Rushmoor",
                             "Rutland" = "Rutland",
                             "Ryedale" = "Ryedale",
                             "Salford" = "Salford",
                             "Sandwell" = "Sandwell",
                             "Scarborough" = "Scarborough",
                             "Sedgemoor" = "Sedgemoor",
                             "Sefton" = "Sefton",
                             "Selby" = "Selby",
                             "Sevenoaks" = "Sevenoaks",
                             "Sheffield" = "Sheffield",
                             "Shropshire" = "Shropshire",
                             "Slough" = "Slough",
                             "Solihull" = "Solihull",
                             "Somerset West and Taunton" = "Somerset West and Taunton",
                             "South Cambridgeshire" = "South Cambridgeshire",
                             "South Derbyshire" = "South Derbyshire",
                             "South Gloucestershire" = "South Gloucestershire",
                             "South Hams" = "South Hams",
                             "South Holland" = "South Holland",
                             "South Kesteven" = "South Kesteven",
                             "South Lakeland" = "South Lakeland",
                             "South Norfolk" = "South Norfolk",
                             "South Northamptonshire" = "South Northamptonshire",
                             "South Oxfordshire" = "South Oxfordshire",
                             "South Ribble" = "South Ribble",
                             "South Somerset" = "South Somerset",
                             "South Staffordshire" = "South Staffordshire",
                             "South Tyneside" = "South Tyneside",
                             "Southampton" = "Southampton",
                             "Southend-On-Sea" = "Southend-On-Sea",
                             "Southwark" = "Southwark",
                             "Spelthorne" = "Spelthorne",
                             "St Albans City" = "St Albans City",
                             "St Helens" = "St Helens",
                             "Stafford" = "Stafford",
                             "Staffordshire Moorlands" = "Staffordshire Moorlands",
                             "Stevenage" = "Stevenage",
                             "Stockport" = "Stockport",
                             "Stockton On Tees" = "Stockton On Tees",
                             "Stoke-On-Trent" = "Stoke-On-Trent",
                             "Stratford-on-Avon" = "Stratford-on-Avon",
                             "Stroud" = "Stroud",
                             "Sunderland" = "Sunderland",
                             "Surrey Heath" = "Surrey Heath",
                             "Sutton" = "Sutton",
                             "Swale" = "Swale",
                             "Swansea" = "Swansea",
                             "Swindon" = "Swindon",
                             "Tameside" = "Tameside",
                             "Tamworth" = "Tamworth",
                             "Tandridge" = "Tandridge",
                             "Teignbridge" = "Teignbridge",
                             "Telford and Wrekin Council" = "Telford and Wrekin Council",
                             "Tendring" = "Tendring",
                             "Test Valley" = "Test Valley",
                             "Tewkesbury" = "Tewkesbury",
                             "Thanet" = "Thanet",
                             "Three Rivers" = "Three Rivers",
                             "Thurrock" = "Thurrock",
                             "Tonbridge and Malling" = "Tonbridge and Malling",
                             "Torbay" = "Torbay",
                             "Torfaen" = "Torfaen",
                             "Torridge" = "Torridge",
                             "Tower Hamlets" = "Tower Hamlets",
                             "Trafford" = "Trafford",
                             "Tunbridge Wells" = "Tunbridge Wells",
                             "Uttlesford" = "Uttlesford",
                             "Vale of Glamorgan" = "Vale of Glamorgan",
                             "Vale of White Horse" = "Vale of White Horse",
                             "Wakefield" = "Wakefield",
                             "Walsall" = "Walsall",
                             "Waltham Forest" = "Waltham Forest",
                             "Wandsworth" = "Wandsworth",
                             "Warrington" = "Warrington",
                             "Warwick" = "Warwick",
                             "Watford" = "Watford",
                             "Waverley" = "Waverley",
                             "Wealden" = "Wealden",
                             "Wellingborough" = "Wellingborough",
                             "Welwyn Hatfield" = "Welwyn Hatfield",
                             "West Berkshire" = "West Berkshire",
                             "West Devon" = "West Devon",
                             "West Lancashire" = "West Lancashire",
                             "West Lindsey" = "West Lindsey",
                             "West Oxfordshire" = "West Oxfordshire",
                             "West Suffolk" = "West Suffolk",
                             "Westminster" = "Westminster",
                             "Wigan" = "Wigan",
                             "Wiltshire" = "Wiltshire",
                             "Winchester City" = "Winchester City",
                             "Windsor and Maidenhead" = "Windsor and Maidenhead",
                             "Wirral" = "Wirral",
                             "Woking" = "Woking",
                             "Wokingham" = "Wokingham",
                             "Wolverhampton" = "Wolverhampton",
                             "Worcester City" = "Worcester City",
                             "Worthing" = "Worthing",
                             "Wrexham" = "Wrexham",
                             "Wychavon" = "Wychavon",
                             "Wyre Forest" = "Wyre Forest",
                             "Wyre" = "Wyre",
                             "York" = "York")

All_Scotland_Area = list("Aberdeen City" = "Aberdeen City",
                         "Aberdeenshire" = "Aberdeenshire",
                         "Angus" = "Angus",
                         "Argyll and Bute" = "Argyll and Bute",
                         "Clackmannanshire" = "Clackmannanshire",
                         "Comhairle nan Eilean Siar (Western Isles)" = "Comhairle nan Eilean Siar (Western Isles)",
                         "Dumfries and Galloway" = "Dumfries and Galloway",
                         "Dundee City" = "Dundee City",
                         "East Ayrshire" = "East Ayrshire",
                         "East Dunbartonshire" = "East Dunbartonshire",
                         "East Lothian" = "East Lothian",
                         "East Renfrewshire" = "East Renfrewshire",
                         "Edinburgh (City of)" = "Edinburgh (City of)",
                         "Falkirk" = "Falkirk",
                         "Fife" = "Fife",
                         "Glasgow City" = "Glasgow City",
                         "Highland" = "Highland",
                         "Inverclyde" = "Inverclyde",
                         "Midlothian" = "Midlothian",
                         "Moray" = "Moray",
                         "North Ayrshire" = "North Ayrshire",
                         "North Lanarkshire" = "North Lanarkshire",
                         "Orkney Islands" = "Orkney Islands",
                         "Perth and Kinross" = "Perth and Kinross",
                         "Renfrewshire" = "Renfrewshire",
                         "Scottish Borders" = "Scottish Borders",
                         "Shetland Islands" = "Shetland Islands",
                         "South Ayrshire" = "South Ayrshire",
                         "South Lanarkshire" = "South Lanarkshire",
                         "Stirling" = "Stirling",
                         "West Dunbartonshire" = "West Dunbartonshire",
                         "West Lothian" = "West Lothian")

All_Area = c(All_non_Scotland_Area, All_Scotland_Area)
All_Area = All_Area[order(names(All_Area))]


Types_of_Business = list("Distributors/Transporters" = "Distributors/Transporters",
                         "Farmers/growers" = "Farmers/growers",
                         "Hospitals/Childcare/Caring Premises" = "Hospitals/Childcare/Caring Premises",
                         "Hotel/bed & breakfast/guest house" = "Hotel/bed & breakfast/guest house",
                         "Importers/Exporters" = "Importers/Exporters",
                         "Manufacturers/packers" = "Manufacturers/packers",
                         "Mobile caterer" = "Mobile caterer",
                         "Other catering premises" = "Other catering premises",
                         "Pub/bar/nightclub" = "Pub/bar/nightclub",
                         "Restaurant/Cafe/Canteen" = "Restaurant/Cafe/Canteen",
                         "Retailers - other" = "Retailers - other",
                         "Retailers - supermarkets/hypermarkets" = "Retailers - supermarkets/hypermarkets",
                         "School/college/university" = "School/college/university",
                         "Takeaway/sandwich shop" = "Takeaway/sandwich shop")

Non_Scotland_Rating = list("0"="0",
                           "1"="1", 
                           "2"="2", 
                           "3"="3", 
                           "4"="4",
                           "5"="5",
                           "Awaiting Inspection"="Awaiting Inspection",
                           "Awaiting Publication"="Awaiting Publication",
                           "Exempt"="Exempt")

Scotland_Rating = list("Pass and Eat Safe"="Pass and Eat Safe",
                       "Pass"="Pass", 
                       "Improvement Required"="Improvement Required", 
                       "Exempt"="Exempt", 
                       "Awaiting Inspection"="Awaiting Inspection",
                       "Awaiting Publication"="Awaiting Publication")

save(All_Area,All_non_Scotland_Area,All_Scotland_Area,Non_Scotland_Rating,Scotland_Rating,Types_of_Business, file = "drop_list_option.RData")
```

We also prepared the drop lists option and store them in a *RData* file. (We are only showing the drop list for *Rating in Scotland* here, while other drop lists option are produced similarly)
```{r}
Scotland_Rating = list("Pass and Eat Safe"="Pass and Eat Safe",
                       "Pass"="Pass", 
                       "Improvement Required"="Improvement Required", 
                       "Exempt"="Exempt", 
                       "Awaiting Inspection"="Awaiting Inspection",
                       "Awaiting Publication"="Awaiting Publication")

save(All_Area,All_non_Scotland_Area,All_Scotland_Area,Non_Scotland_Rating,Scotland_Rating,Types_of_Business, file = "drop_list_option.RData")
# Saving the RData file 
```
